version: "{build}"

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 12


platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install -g lerna
  - npm install

build: off

before_test:
  - npm install -g grunt-cli

test_script:
  - ps: "grunt test # PowerShell"
  - cmd: grunt test

cache:
  - node_modules

matrix:
  fast_finish: true
